/** Declaration file generated by dts-gen */

export function BadRequest(customMessage: any): any;

export function CustomError(): any;

export function InternalServerError(customMessage: any): any;

export function NotAuthorized(customMessage: any): any;

export function NotFound(customMessage: any): any;

export function ServiceUnavailable(customMessage: any): any;

export namespace BadRequest {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace CustomError {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace InternalServerError {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace NotAuthorized {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace NotFound {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

export namespace ServiceUnavailable {
    const stackTraceLimit: number;

    function captureStackTrace(p0: any, p1: any): any;

}

